#########################################
# Author: Ali Dashti 
# Site: https://dashti.dev
# Source: https://github.com/XxDaShTixX/McPlugin-ArrowTNT/
#
# EnableArrowTNT: Enable or disable the plugin
# Explosion Multiplier : Controls the size of explosion
# WorldList : List of worlds to enable this plugin in
#########################################
EnableArrowTNT: true
ExplosionMultiplier: 1.0
AllowWorldList:
  - world
  - world_nether
  - world_the_end
